encrypt

diff --git a/php8.1.13/DockerFile_debian b/php8.1.13/DockerFile_debian
--- a/php8.1.13/DockerFile_debian
+++ b/php8.1.13/DockerFile_debian
@@ -10,56 +10,56 @@ FROM debian:buster-slim
 # https://github.com/docker-library/php/pull/542
 RUN set -eux; \
 	{ \
-		echo 'Package: php*'; \
-		echo 'Pin: release *'; \
-		echo 'Pin-Priority: -1'; \
+	echo 'Package: php*'; \
+	echo 'Pin: release *'; \
+	echo 'Pin-Priority: -1'; \
 	} > /etc/apt/preferences.d/no-debian-php
 
 # dependencies required for running "phpize"
 # (see persistent deps below)
 ENV PHPIZE_DEPS \
-		autoconf \
-		dpkg-dev \
-		file \
-		g++ \
-		gcc \
-		libc-dev \
-		make \
-		pkg-config \
-		re2c
+	autoconf \
+	dpkg-dev \
+	file \
+	g++ \
+	gcc \
+	libc-dev \
+	make \
+	pkg-config \
+	re2c
 
 # persistent / runtime deps
 RUN set -eux; \
-    # echo "# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释" > /etc/apt/sources.list;\
-    # echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" >> /etc/apt/sources.list;\
-    # echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" >> /etc/apt/sources.list;\
-    # echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free" >> /etc/apt/sources.list;\
-    # echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free" >>  etc/apt/sources.list; \
-    # echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list;\
-    # echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list;\
-    # echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" >> /etc/apt/sources.list;\
-    # echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" >>  /etc/apt/sources.list; \
+	# echo "# 默认注释了源码镜像以提高 apt update 速度，如有需要可自行取消注释" > /etc/apt/sources.list;\
+	# echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" >> /etc/apt/sources.list;\
+	# echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster main contrib non-free" >> /etc/apt/sources.list;\
+	# echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free" >> /etc/apt/sources.list;\
+	# echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-updates main contrib non-free" >>  etc/apt/sources.list; \
+	# echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list;\
+	# echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ buster-backports main contrib non-free" >> /etc/apt/sources.list;\
+	# echo "deb https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" >> /etc/apt/sources.list;\
+	# echo "deb-src https://mirrors.tuna.tsinghua.edu.cn/debian-security buster/updates main contrib non-free" >>  /etc/apt/sources.list; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
-		$PHPIZE_DEPS \
-		ca-certificates \
-		curl \
-		xz-utils \
-        openssl \
-        libargon2-dev \
-        coreutils \
-        libticonv-dev \
-        libsodium-dev \
-        libxml2-dev \
-        libmcrypt-dev \
-        libzip-dev \
-        cmake \
-        librabbitmq-dev \
-        libpng-dev \
-        tzdata; \
-        cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;\
-        echo "Asia/Shanghai" > /etc/timezone;\
-	    rm -rf /var/lib/apt/lists/*
+	$PHPIZE_DEPS \
+	ca-certificates \
+	curl \
+	xz-utils \
+	openssl \
+	libargon2-dev \
+	coreutils \
+	libticonv-dev \
+	libsodium-dev \
+	libxml2-dev \
+	libmcrypt-dev \
+	libzip-dev \
+	cmake \
+	librabbitmq-dev \
+	libpng-dev \
+	tzdata; \
+	cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;\
+	echo "Asia/Shanghai" > /etc/timezone;\
+	rm -rf /var/lib/apt/lists/*
 
 ENV PHP_INI_DIR /usr/local/etc/php
 
@@ -70,6 +70,8 @@ ENV PHP_CFLAGS="-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_
 ENV PHP_CPPFLAGS="$PHP_CFLAGS"
 
 ENV PHP_LDFLAGS="-Wl,-O1 -pie"
+
+ENV ENCRY_VERSION=2.0.4
 
 
 ENV PHP_INSTALL \
@@ -89,14 +91,15 @@ ENV PHP_INSTALL \
 	gettext \
 	exif
 
-    
+
 RUN set -eux; \
 	mkdir -p "$PHP_INI_DIR/conf.d"; \
-# allow running as an arbitrary user (https://github.com/docker-library/php/issues/743)
+	# allow running as an arbitrary user (https://github.com/docker-library/php/issues/743)
 	[ ! -d /var/www ]; \
 	mkdir -p /var/www; \
 	chown www-data:www-data /var/www; \
 	chmod 777 /var/www; 
+
 
 COPY docker-php-source /usr/local/bin/
 
@@ -104,7 +107,7 @@ COPY php.tar.xz  /usr/src
 
 COPY php-amqp.tar.gz /usr/src
 
-COPY php-ext-encry-1.0.tar.gz /usr/src
+COPY "php-ext-encry-${ENCRY_VERSION}.tar.gz" /usr/src
 
 COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/
 
@@ -113,29 +116,28 @@ RUN set -eux; \
 	savedAptMark="$(apt-mark showmanual)"; \
 	apt-get update; \
 	apt-get install -y --no-install-recommends \
-		libargon2-dev \
-		libcurl4-openssl-dev \
-		libonig-dev \
-		libreadline-dev \
-		libsodium-dev \
-		libsqlite3-dev \
-		libssl-dev \
-		libxml2-dev \
-		zlib1g-dev \
+	libargon2-dev \
+	libcurl4-openssl-dev \
+	libonig-dev \
+	libreadline-dev \
+	libsodium-dev \
+	libsqlite3-dev \
+	libssl-dev \
+	libxml2-dev \
+	zlib1g-dev \
 	; \
-	\
 	export \
-		CFLAGS="$PHP_CFLAGS" \
-		CPPFLAGS="$PHP_CPPFLAGS" \
-		LDFLAGS="$PHP_LDFLAGS" \
+	CFLAGS="$PHP_CFLAGS" \
+	CPPFLAGS="$PHP_CPPFLAGS" \
+	LDFLAGS="$PHP_LDFLAGS" \
 	; \
 	docker-php-source extract; \
 	cd /usr/src/php; \
 	gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
 	debMultiarch="$(dpkg-architecture --query DEB_BUILD_MULTIARCH)"; \
-# https://bugs.php.net/bug.php?id=74125
+	# https://bugs.php.net/bug.php?id=74125
 	if [ ! -d /usr/include/curl ]; then \
-		ln -sT "/usr/include/$debMultiarch/curl" /usr/local/include/curl; \
+	ln -sT "/usr/include/$debMultiarch/curl" /usr/local/include/curl; \
 	fi; \
 	./configure \
 	--build="$gnuArch" \
@@ -163,6 +165,7 @@ RUN set -eux; \
 	--enable-fpm \
 	--with-fpm-user=www-data \
 	--with-fpm-group=www-data \
+	--enable-fd-setsize=3096 \
 	; \
 	make -j "$(nproc)"; \
 	make install; \
@@ -174,9 +177,9 @@ RUN set -eux; \
 	./configure  --with-php-config=/usr/local/bin/php-config; \
 	make -j "$(nproc)"; \
 	make install; \
-	mkdir -p /usr/src/php-ext-encry-1.0; \
-	tar -zxvf /usr/src/php-ext-encry-1.0.tar.gz -C /usr/src; \
-	cd  /usr/src/php-ext-encry-1.0; \
+	mkdir -p "/usr/src/php-ext-encry-${ENCRY_VERSION}"; \
+	tar -zxvf "/usr/src/php-ext-encry-${ENCRY_VERSION}.tar.gz" -C /usr/src; \
+	cd  "/usr/src/php-ext-encry-${ENCRY_VERSION}"; \
 	/usr/local/bin/phpize; \
 	./configure  --with-php-config=/usr/local/bin/php-config; \
 	make -j "$(nproc)"; \
@@ -214,50 +217,59 @@ COPY docker-php-ext-* docker-php-entrypoint /usr/local/bin/
 RUN docker-php-ext-enable sodium
 
 ENTRYPOINT ["docker-php-entrypoint"]
-WORKDIR /var/www
+WORKDIR /home/www-data
 
 RUN set -eux; \
+	apt-get update;\
+	apt-get install nodejs npm -y;\
+	npm install pm2 -g;\
 	cd /usr/local/etc; \
 	if [ -d php-fpm.d ]; then \
-		# for some reason, upstream's php-fpm.conf.default has "include=NONE/etc/php-fpm.d/*.conf"
-		sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
-		cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
+	# for some reason, upstream's php-fpm.conf.default has "include=NONE/etc/php-fpm.d/*.conf"
+	sed 's!=NONE/!=!g' php-fpm.conf.default | tee php-fpm.conf > /dev/null; \
+	cp php-fpm.d/www.conf.default php-fpm.d/www.conf; \
 	else \
-		# PHP 5.x doesn't use "include=" by default, so we'll create our own simple config that mimics PHP 7+ for consistency
-		mkdir php-fpm.d; \
-		cp php-fpm.conf.default php-fpm.d/www.conf; \
-		{ \
-			echo '[global]'; \
-			echo 'include=etc/php-fpm.d/*.conf'; \
-		} | tee php-fpm.conf; \
+	# PHP 5.x doesn't use "include=" by default, so we'll create our own simple config that mimics PHP 7+ for consistency
+	mkdir php-fpm.d; \
+	cp php-fpm.conf.default php-fpm.d/www.conf; \
+	{ \
+	echo '[global]'; \
+	echo 'include=etc/php-fpm.d/*.conf'; \
+	} | tee php-fpm.conf; \
 	fi; \
 	{ \
-		echo '[global]'; \
-		echo 'error_log = /proc/self/fd/2'; \
-		echo; echo '; https://github.com/docker-library/php/pull/725#issuecomment-443540114'; echo 'log_limit = 8192'; \
-		echo; \
-		echo '[www]'; \
-		echo '; if we send this to /proc/self/fd/1, it never appears'; \
-		echo 'access.log = /proc/self/fd/2'; \
-		echo; \
-		echo 'clear_env = no'; \
-		echo; \
-		echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
-		echo 'catch_workers_output = yes'; \
-		echo 'decorate_workers_output = no'; \
+	echo '[global]'; \
+	echo 'error_log = /proc/self/fd/2'; \
+	echo; echo '; https://github.com/docker-library/php/pull/725#issuecomment-443540114'; echo 'log_limit = 8192'; \
+	echo; \
+	echo '[www]'; \
+	echo '; if we send this to /proc/self/fd/1, it never appears'; \
+	echo 'access.log = /proc/self/fd/2'; \
+	echo; \
+	echo 'clear_env = no'; \
+	echo; \
+	echo '; Ensure worker stdout and stderr are sent to the main error log.'; \
+	echo 'catch_workers_output = yes'; \
+	echo 'decorate_workers_output = no'; \
 	} | tee php-fpm.d/docker.conf; \
 	{ \
-		echo '[global]'; \
-		echo 'daemonize = no'; \
-		echo; \
-		echo '[www]'; \
-		echo 'listen = 9000'; \
+	echo '[global]'; \
+	echo 'daemonize = no'; \
+	echo; \
+	echo '[www]'; \
+	echo 'listen = 9000'; \
 	} | tee php-fpm.d/zz-docker.conf; \
 	mkdir -p "$PHP_INI_DIR/conf.d"; \
 	{ \
-		echo '; https://github.com/docker-library/php/issues/878#issuecomment-938595965'; \
-		echo 'fastcgi.logging = Off'; \
+	echo '; https://github.com/docker-library/php/issues/878#issuecomment-938595965'; \
+	echo 'fastcgi.logging = Off'; \
 	} > "$PHP_INI_DIR/conf.d/docker-fpm.ini"
+
+# RUN set -eux; \
+# 	cd $PHP_INI_DIR; \
+# 	sed -i  's/pm = dynamic/pm = static/g' "$PHP_INI_DIR/php-fpm.d/www.conf"; \
+# 	sed -i  's/pm.max_children = 5/pm.max_children = 10 /g' "$PHP_INI_DIR/php-fpm.d/www.conf";\
+# 	sed -i  's/expose_php = On/expose_php = Off /g' "$PHP_INI_DIR/php.ini";
 
 # Override stop signal to stop process gracefully
 # https://github.com/php/php-src/blob/17baa87faddc2550def3ae7314236826bc1b1398/sapi/fpm/php-fpm.8.in#L163
